apiVersion: v1
kind: ReplicationController
metadata:
  name: springbootapp
spec:
  replicas: 1
  selector:
    app: springbootapp
  template:
    metadata:
      name: springbootapp
      labels:
        app: springbootapp
    spec:
      containers:
      - name: springbootapp
        image:  gcr.io/orbital-expanse-161322/springbootweb
        ports:
        - containerPort: 8080
